# Generated by Django 4.1.5 on 2023-01-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='prior',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task',
        ),
    ]
