# Generated by Django 4.1.5 on 2023-01-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_priority_task_prior_rename_name_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prior',
            new_name='priority',
        ),
    ]
