# Generated by Django 4.1.5 on 2023-02-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_rename_availabe_product_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='category',
        ),
    ]
